# Toán ứng dụng và thống kê - Project 4: Diagonalizable matrix

**Họ và tên:** Trần Thảo Ngân

**MSSV:** 22120225

**Lớp:** 22/3

## Đề bài

**Bài 1:**

&emsp;Cho A là ma trận có thể chéo hóa được. Sinh viên viết chương trình tìm ma trận chéo $P$, $P^{-1}$ và ma trận đường chéo $D$, biết rằng $A = PDP^{-1}$

&emsp;*Lưu ý:* sinh viên phải sử dụng thuật toán chéo hóa đã được hướng dẫn trong phần bài tập. Sinh viên không được dùng các hàm có sẵn của các thư viện để chéo hóa.

**Bài 2: Mở rộng:**

&emsp;&emsp;• Tìm hiểu hàm/ phương thức tương ứng của các thư viện và thực hiện nó, so sánh kết quả.

&emsp;&emsp;• Tìm hiểu và trình bày ứng dụng của chéo hóa.

## Giải thuật

**Bước 1:** Tìm đa thức đặc trưng $det(A - λI)$. Nếu $P_{A}(λ)$ có tổng các lũy thừa khác $n$ thì $A$ không chéo hóa được và kết thúc, ngược lại chuyển sang bước tiếp theo.

&emsp;&emsp;+ Đối với ma trận vuông 2x2, đa thức đặc trưng được tính bằng công thức:

$$
P_A(\lambda) = \det(A - \lambda I) = \det\begin{pmatrix} a_{11}-\lambda & a_{12} \ a_{21} & a_{22}-\lambda \end{pmatrix} = (\lambda - a_{11})(\lambda - a_{22}) - a_{12}a_{21}
$$

&emsp;&emsp;+ Đối với ma trận vuông 3x3, đa thức đặc trưng được tính bằng công thức:

$$
P_A(\lambda) = \det(A - \lambda I) = \det\begin{pmatrix} a_{11}-\lambda & a_{12} & a_{13} \ a_{21} & a_{22}-\lambda & a_{23} \ a_{31} & a_{32} & a_{33}-\lambda \end{pmatrix} 
$$
$$
= (\lambda - a_{11})[(\lambda - a_{22})(\lambda - a_{33}) - a_{23}a_{32}] - a_{12}[(\lambda - a_{21})(\lambda - a_{33}) - a_{23}a_{31}] + a_{13}[(\lambda - a_{21})(\lambda - a_{32}) - a_{22}a_{31}]
$$

Sau khi tính được đa thức đặc trưng $P_A(\lambda)$, ta có thể tìm các giá trị riêng của ma trận bằng cách giải phương trình $P_A(\lambda) = 0$.

**Bước 2:** Tìm tất cả các nghiệm $λ_{i}$ của phương trình đa thức đặc trưng. 

&emsp;&emsp;+ Với mỗi trị riêng $λ_{i}$ tìm cơ sở và số chiều cho không gian nghiệm phương trình  $(A - λI_{n})X = 0$. 

&emsp;&emsp;+ Nếu mỗi $λ_{i}$ số chiều không gian nghiệm nhỏ hơn lũy thừa của $λ_{i}$ trong đa thức đặc trưng thì $A$ không chéo hóa được và thuật toán kết thúc, ngược lại chuyển sang bước 3.
    
**Bước 3:** Với các vector trong cơ sở không gian nghiệm tìm được ở bước 2, ta đặt ma trận $P$ là ma trận có được bằng cách dựng các vector thành các cột.  Khi đó ma trận $P$ làm chéo $A$ và $P^{-1}AP$ là ma trận đường chép $D$.



### Bài 1

In [32]:
import numpy as np


def Gauss_elimination(A):
    m = len(A)      
    n = len(A[0])  
    flag = 0        
    for r in range(m):
        if flag >= n:
            return A
        i = r
        while A[i][flag] == 0:
            i += 1
            if i == m:
                i = r
                flag += 1
                if n == flag:
                    return A      
        A[i], A[r] = A[r], A[i]
        lv = A[r][flag]
        for i in range(len(A[i])):
            A[r][i] /= float(lv)
        for i in range(m):
            if i!= r:
                lv = A[i][flag]
                for j in range(len(A[i])):
                    A[i][j] -= lv * A[r][j]
        flag += 1
    return A

def solve3(A):
    A = Gauss_elimination(A)
    if(A[2][2] == 0):
        x3 = 1
        x2 = -A[1][2]/A[1][1]
        x1 = (- A[0][2]*x3 - A[0][1]*x2)/A[0][0]
    else:
        x3 = 0
        if (A[1][1] == 0):
            x2 = 1
            x1 = (- A[0][2]*x3 - A[0][1]*x2)/A[0][0]
        else:
            x2 = 0
            x1 = 0
    return float(x1), float(x2), float(x3)


# Chéo hóa ma trận
def Diagonalizable_matrix(A):
    if(len(A) == 2):
        a = 1
        b = -(A[0][0] + A[1][1])
        c = A[0][0]*A[1][1] - A[0][1]*A[1][0]
        if b*b - 4*a*c == 0:
            return "Ma tran khong cheo hoa duoc"
        elif b*b - 4*a*c != 0:
            lambda_1 = (-b + (b*b - 4*a*c)**0.5)/(2*a)
            lambda_2 = (-b - (b*b - 4*a*c)**0.5)/(2*a)
        B1 = [[A[0][0] - lambda_1, A[0][1]], [A[1][0], A[1][1] - lambda_1]]
        x1 = - B1[0][1] / B1[0][0]
        x2 = 1
        B2 = [[A[0][0] - lambda_2, A[0][1]], [A[1][0], A[1][1] - lambda_2]]
        y1 = - B2[0][1] / B2[0][0]
        y2 = 1
        P = [[x1, y1], [x2, y2]]
        D = [[lambda_1, 0], [0, lambda_2]]
        P_inv = np.linalg.inv(P)
        return P, D, P_inv
    else:
        a = -1
        b = A[0][0] + A[1][1] + A[2][2]
        c = -(A[0][0]*A[2][2] + A[2][2]*A[1][1] + A[0][0]*A[1][1] - A[0][2]*A[2][0] - A[1][2]*A[2][1] - A[0][1]*A[1][0])
        d = A[0][0]*A[1][1]*A[2][2] + A[0][1]*A[1][2]*A[2][0] + A[0][2]*A[1][0]*A[2][1] - A[0][0]*A[1][2]*A[2][1] - A[0][1]*A[1][0]*A[2][2] - A[0][2]*A[1][1]*A[2][0]
        x = sp.symbols('x')
        equation = a*x**3 + b*x**2 + c*x + d
        roots = sp.solve(equation, x)
        lambda_1 = roots[0]
        lambda_2 = roots[1]
        lambda_3 = roots[2]
        D = [[lambda_1, 0, 0], [0, lambda_2, 0], [0, 0, lambda_3]]
        B1 = [[A[0][0] - lambda_1, A[0][1], A[0][2]], [A[1][0], A[1][1] - lambda_1, A[1][2]], [A[2][0], A[2][1], A[2][2] - lambda_1]]
        B2 = [[A[0][0] - lambda_2, A[0][1], A[0][2]], [A[1][0], A[1][1] - lambda_2, A[1][2]], [A[2][0], A[2][1], A[2][2] - lambda_2]]
        B3 = [[A[0][0] - lambda_3, A[0][1], A[0][2]], [A[1][0], A[1][1] - lambda_3, A[1][2]], [A[2][0], A[2][1], A[2][2] - lambda_3]]
        x1, x2, x3 = solve3(B1)
        y1, y2, y3 = solve3(B2)
        z1, z2, z3 = solve3(B3)
        P = [[x1, y1, z1], [x2, y2, z2], [x3, y3, z3]]
        P_inv = np.linalg.inv(P)
        return P, D, P_inv

P, D, P_inv = Diagonalizable_matrix([[5, -1, 1], [-1, 2, -2], [1, -2, 2]])
print("P = ", P)
print("D = ", D)
print("P^-1 = ", P_inv)



P =  [[0.0, -1.0, 2.0], [1.0, -1.0, -1.0], [1.0, 1.0, 1.0]]
D =  [[0, 0, 0], [0, 3, 0], [0, 0, 6]]
P^-1 =  [[ 0.          0.5         0.5       ]
 [-0.33333333 -0.33333333  0.33333333]
 [ 0.33333333 -0.16666667  0.16666667]]


### Bài 2

In [33]:
import numpy as np

def diagonalize_matrix(A):
    eigenvalues, eigenvectors = np.linalg.eig(A)

    sorted_idx = np.argsort(eigenvalues)[::-1]
    eigenvalues = eigenvalues[sorted_idx]
    eigenvectors = eigenvectors[:, sorted_idx]
    
    P_matrix = eigenvectors
    P_inv_matrix = np.linalg.inv(P_matrix)
    D_matrix = np.diag(eigenvalues)
    
    return P_matrix, D_matrix, P_inv_matrix

A = np.array([[5, 2],
              [9, 2]])

P, D, P_inv = diagonalize_matrix(A)

print("P:")
print(P)
print("\nD:")
print(D)
print("\nP^-1:")
print(P_inv)

P:
[[ 0.5547002  -0.31622777]
 [ 0.83205029  0.9486833 ]]

D:
[[ 8.  0.]
 [ 0. -1.]]

P^-1:
[[ 1.20185043  0.40061681]
 [-1.05409255  0.70272837]]


### Ứng dụng của chéo hóa:

&emsp;&emsp;**1. Ứng dụng trong machine learning:**

&emsp;&emsp;&emsp;&emsp;- Phân tích thành phần chính (PCA): Bằng cách chéo hóa ma trận hiệp phương sai của dữ liệu, PCA tìm ra các thành phần chính (principal components) của dữ liệu, giúp biểu diễn dữ liệu ban đầu bằng các thành phần có biểu diễn dữ liệu tốt nhất.

&emsp;&emsp;&emsp;&emsp;- Trích xuất đặc trưng (Feature Extraction): Bằng cách chéo hóa ma trận tương quan hoặc ma trận tương đồng, các đặc trưng quan trọng có thể được trích xuất.

&emsp;&emsp;&emsp;&emsp;- Giảm nhiễu (Denoising). 

&emsp;&emsp;&emsp;&emsp;- Phân loại ảnh và nhận dạng (Image Classification và Recognition).

&emsp;&emsp;&emsp;&emsp;- Xử lý ngôn ngữ tự nhiên (Natural Language Processing - NLP).

&emsp;&emsp;&emsp;&emsp;- Gom cụm (Clustering).

&emsp;&emsp;**2. Ứng dụng trong vật lý, kỹ thuật, điện tử viễn thông:**

&emsp;&emsp;&emsp;&emsp;- Trong vật lý, chéo hóa ma trận có thể được sử dụng để phân tích dữ liệu từ các thí nghiệm vật lý. 

&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;+ *Ví dụ, trong phân tích dữ liệu từ cảm biến, chéo hóa ma trận có thể được sử dụng để tìm ra các đặc trưng quan trọng và loại bỏ nhiễu từ dữ liệu đo.*

&emsp;&emsp;&emsp;&emsp;- Trong ngành điện tử và viễn thông, chéo hóa ma trận có thể được sử dụng để phân tích dữ liệu từ các hệ thống truyền thông và mạng máy tính. 

&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;+ *Ví dụ, trong phân tích dữ liệu từ mạng máy tính, chéo hóa ma trận có thể được sử dụng để phân tích mối quan hệ giữa các máy tính và người dùng trên mạng.*

&emsp;&emsp;**3. Ứng dụng trong y học và sinh học:**

&emsp;&emsp;&emsp;&emsp;- Trong y học và sinh học, chéo hóa ma trận có thể được sử dụng để phân tích dữ liệu gen và dữ liệu sinh học.

&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;+ *Ví dụ, trong phân tích dữ liệu gen, chéo hóa ma trận có thể được sử dụng để phân tích biểu hiện gen và tìm ra các biểu hiện gen quan trọng.*

&emsp;&emsp;**4. Ứng dụng trong robotics và tự động hóa:**

&emsp;&emsp;&emsp;&emsp;- Trong robotics và tự động hóa, chéo hóa ma trận có thể được sử dụng để phân tích dữ liệu từ các cảm biến và hệ thống điều khiển.

&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;+ *Ví dụ, trong robotics, chéo hóa ma trận có thể được sử dụng để phân tích dữ liệu từ các cảm biến và điều khiển chuyển động của robot.*

## Mô tả ý tưởng

**Bước 1.** Chia bài toán thành 2 trường hợp: ma trận 2x2 và ma trận 3x3.

**Bước 2.** Xây dựng phương trình đa thức $P_A(\lambda) = 0$. Sau đó tìm ra các nghiệm bằng cách giải phương trình bậc 2, bậc 3. Ta tìm được các trị riêng.

**Bước 3.** Tương ứng với mỗi trị riêng, ta có một ma trận $(A - λI)$ tương ứng. Sử dụng phép khử Gauss để giải phương trình, sau đó ta xác định được các vector riêng tương ứng.

**Bước 4.** Sắp xếp các trị riêng thành ma trận đường chéo $D$. Xếp các vector riêng thành các cột, ta được ma trận $P$. Sử dụng hàm **np.linalg.inv** ta tìm được ma trận $P^{-1}$.

## Mô tả các hàm

### Bài 1:

**Các hàm phụ trợ:**

&emsp;&emsp;**def Gauss_elimination(A):**: Chuyển đổi ma trận A thành ma trận bậc thang.

&emsp;&emsp;**def solve3(A):**: Tìm các vector riêng.

**Hàm chính:**

&emsp;&emsp;**def Diagonalizable_matrix(A):** Hàm chéo hóa ma trận $A$ thành $A = PDP^{-1}$ (không dùng thư viện)

### Bài 2: 

&emsp;&emsp;**np.linalg.eig():** Tìm trị riêng và vector riêng

&emsp;&emsp;**np.argsort():** Sắp xếp trị riêng giảm dần

&emsp;&emsp;**np.linalg.inv():** Tìm ma trận nghịch đảo 

&emsp;&emsp;**np.diag():** Tạo ma trận đường chéo