# Toán ứng dụng và thống kê - Project 3: Gram – Schmidt

**Họ và tên:** Trần Thảo Ngân

**MSSV:** 22120225

**Lớp:** 22/3

## Đề bài

**Bài 1:**

&emsp;Cho A là ma trận có thể phân rã $QR$. Sinh viên viết chương trình in ra ma trận $Q$ và $R$, biết rằng $A = QR$.

&emsp;*Lưu ý:* sinh viên phải sử dụng thuật toán **Gram – Schmidt** đã được hướng dẫn trong phần bài tập. Sinh viên không được dùng các hàm có sẵn của các thư viện để phân rã QR.

**Bài 2: Mở rộng:**

&emsp;&emsp;• Tìm hiểu hàm/ phương thức tương ứng của các thư viện và thực hiện nó, so sánh kết quả.

&emsp;&emsp;• Tìm hiểu và trình bày ứng dụng của QR decomposition.

### Quy định bài nộp
&emsp;&emsp;• Thực hiện toàn bộ bài làm trên 1 tập tin Jupyter Notebook (.ipynb).

&emsp;&emsp;• Đầu bài phải có phần trình bày thông tin sinh viên và giải thuật theo giống yêu cầu của Bài tập 18.

&emsp;&emsp;• Cuối bài phải có phần mô tả ý tưởng thực hiện và mô tả các hàm.
    
### Quy định chấm bài
Những trường hợp sau đây sẽ bị 0 điểm toàn bộ đồ án:

&emsp;&emsp;• Nộp sai quy định bài nộp.
    
&emsp;&emsp;• Thực thi mã nguồn báo lỗi.

## Giải thuật

**Bước 1. Chuẩn hóa ma trận**

&emsp;&emsp;- Xác định $n$ cột của A = ($u_{0}|u_{1}|...|u_{n-1}$)

&emsp;&emsp;- Trực chuẩn hóa $u_{0}, u_{1}, ..., u_{n-1}$: 

&emsp;&emsp;&emsp;&emsp;+ Với mọi vector $u$ ta thành lập vector $v$: <br>
$$
v_{k+1} = u_{k+1} - \sum_{i=1}^k \frac{<u_{k+1}, v_{i}>}{||v_{i}||^2} v_{i}
$$
        
&emsp;&emsp;&emsp;&emsp;+ Nếu các vector $v$ của A không độc lập tuyến tính thì kết thúc thuật toán. Hệ vector $v$ không độc lập tuyến tính nếu có một vector $v_{i}$ bằng $0$.
        
&emsp;&emsp;&emsp;&emsp;+ Ngược lại, ta nhận được $q_{0}, q_{1},..., q_{n-1}$ là họ trực chuẩn tương ứng.
    
&emsp;&emsp;- Chuẩn hóa từng vector $v$ để thu được họ trực chuẩn $q_{0}, q_{1},..., q_{n-1}$: <br>
$$
q_{i} = \frac{v_{i}}{||v_{i}||}
$$

**Bước 2. Phân rã QR.**

&emsp;&emsp;- Từ bước 1, ta có được ma trận cột trực giao $Q$ = ($q_{1}|q_{2}|...|q_{n}$)

&emsp;&emsp;- Tính các thành phần của ma trận tam giác trên $R$ với $R_{ij}$ = <$u_{i}q_{j}$>, trong đó $i$ là cột và $j$ là hàng của giá trị $R_{ij}$.





### Bài 1

In [58]:
import math

def dot_product(u, v):
    n = len(u)
    sum = 0
    for i in range(n):
        sum += u[i] * v[i]
    return sum

def vector_product(u, v):
    n = len(u)
    result = [0 for _ in range(n)]
    for i in range(n):
        result[i] = u[i] * v
    return result

def vector_subtract(u, v):
    n = len(u)
    result = [0 for _ in range(n)]
    for i in range(n):
        result[i] = u[i] - v[i]
    return result

def vector_devide(u, v):
    n = len(u)
    result = [0 for _ in range(n)]
    for i in range(n):
        result[i] = u[i] / v
    return result

def QR_decomposition(A):
    n = len(A)
    m = len(A[0])
    Q = [[0 for i in range(m)] for j in range(n)]
    R = [[0 for i in range(m)] for j in range(m)]
    u = [[0 for i in range(n)] for j in range(m)]
    v = [[0 for i in range(n)] for j in range(m)]
    q = [[0 for i in range(n)] for j in range(m)]
    a = [0 for i in range(m)]
    # Xác định n cột của A
    for i in range(m):
        for j in range(n):
            u[i][j] = A[j][i]

    # Trực chuẩn hóa u
    for i in range(m):
        if i == 0:
            v[i] = u[i]
            a[i] = dot_product(v[i], v[i])
        else:
            v[i] = u[i]
            for j in range(i):
                v[i] = vector_subtract(v[i], vector_product(v[j], dot_product(u[i], v[j])/a[j]))
            a[i] = dot_product(v[i], v[i])
            if a[i] == 0:
                print("Ma trận không thể phân rã QR")
                return None, None
    
    # Xác định Q
    for i in range(m):
        q[i] = vector_devide(v[i], math.sqrt(a[i]))
    for i in range(m):
        for j in range(n):
            Q[j][i] = q[i][j]

    # Xác định R
    for i in range(m):
        for j in range(m):
            R[i][j] = dot_product(u[j], q[i])
    return Q, R
    

A = [[-1, -1, 1], [1, 3, 3], [-1, -1, 5], [1, 3, 7]]
Q , R = QR_decomposition(A)

print("Q:")
for i in range(len(Q)):
    print(Q[i])

print("R:")
for i in range(len(R)):
    print(R[i])

Q:
[-0.5, 0.5, -0.5]
[0.5, 0.5, -0.5]
[-0.5, 0.5, 0.5]
[0.5, 0.5, 0.5]
R:
[2.0, 4.0, 2.0]
[0.0, 2.0, 8.0]
[0.0, 0.0, 4.0]


### Bài 2

In [55]:
import numpy as np

A = np.array([[-1, -1, 1], [1, 3, 3], [-1, -1, 5], [1, 3, 7]])
Q, R = np.linalg.qr(A)

print("Q:")
print(Q)
print("R:")
print(R)

Q:
[[-0.5 -0.5  0.5]
 [ 0.5 -0.5  0.5]
 [-0.5 -0.5 -0.5]
 [ 0.5 -0.5 -0.5]]
R:
[[ 2.  4.  2.]
 [ 0. -2. -8.]
 [ 0.  0. -4.]]


### Ứng dụng của QR decomposition:

&emsp;&emsp;**1. Xử lý tín hiệu và hình ảnh:**

&emsp;&emsp;&emsp;&emsp;- Trong xử lý tín hiệu, phân tích dữ liệu không gian tần số thường sử dụng phép phân rã QR để giảm chiều dữ liệu, giảm nhiễu tín hiệu bằng cách giảm chiều của tín hiệu, trích xuất các đặc trưng quan trọng của tín hiệu.

&emsp;&emsp;&emsp;&emsp;- Trong xử lý hình ảnh, phép phân rã QR có thể được sử dụng để nén hình ảnh một cách hiệu quả bằng cách giảm số lượng cột của ma trận ảnh.

&emsp;&emsp;**2. Ứng dụng trong machine learning và học máy:**

&emsp;&emsp;&emsp;&emsp;- Trong machine learning, phân rã QR được sử dụng trong các thuật toán học máy như hồi quy tuyến tính để tạo ra các mô hình dự đoán bằng cách giảm chiều dữ liệu.

&emsp;&emsp;&emsp;&emsp;- Trong các thuật toán suy luận ma trận, như phân tích thành phần chính (Principal Component Analysis - PCA), suy biến (Singular Value Decomposition - SVD), phép phân rã QR được sử dụng để giảm chiều dữ liệu và trích xuất các đặc trưng quan trọng.

&emsp;&emsp;&emsp;&emsp;- Ngoài ra, phân rã QR cũng được ứng dụng trong các thuật toán học máy như Rút trích đặc trưng (Feature Extraction), Giảm chiều dữ liệu (Dimensionality Reduction) bằng cách giảm chiều dữ liệu, từ đó rút trích dữ liệu một cách hiệu quả, cải thiện hiệu suất và tăng tốc quá trình huấn luyện mô hình.

&emsp;&emsp;**3. Ứng dụng trong kỹ thuật và khoa học dữ liệu:**

&emsp;&emsp;&emsp;&emsp;- Trong kỹ thuật, phép phân rã QR được sử dụng để giải các hệ phương trình tuyến tính phức tạp trong các ứng dụng kỹ thuật. Trong công nghệ thông tin, phép phân rã QR được sử dụng để tính toán cấu trúc dữ liệu phức tạp và giải quyết các vấn đề liên quan đến xử lý tín hiệu và hình ảnh.

&emsp;&emsp;&emsp;&emsp;- Trong khoa học dữ liệu, phép phân rã QR có thể được sử dụng để chuẩn hóa dữ liệu và giảm chiều dữ liệu trong các tập dữ liệu lớn và phức tạp, giúp cải thiện hiệu suất của các thuật toán máy học và phân tích dữ liệu.

&emsp;&emsp;**4. Ứng dụng trong kỹ thuật tài chính:**

&emsp;&emsp;&emsp;&emsp;- Trong kỹ thuật tài chính, phép phân rã QR được sử dụng để xử lý dữ liệu tài chính phức tạp, bao gồm cả các bảng cân đối kế toán, báo cáo tài chính, và dữ liệu thị trường tài chính; phân tích chuỗi thời gian và dự báo xu hướng tài chính, bao gồm cả dự báo giá cổ phiếu, tỷ giá hối đoái, và lãi suất. 

&emsp;&emsp;&emsp;&emsp;- Nó cũng được sử dụng để phân tích rủi ro tài chính và xây dựng các mô hình quản lý rủi ro trong các công ty và tổ chức tài chính, tối ưu hóa danh mục đầu tư và quản lý danh mục đầu tư cho các nhà đầu tư và quỹ đầu tư.

&emsp;&emsp;**5. Ứng dụng trong điều khiển và tự động hóa:**

&emsp;&emsp;&emsp;&emsp;- Trong lĩnh vực điều khiển và tự động hóa, phép phân rã QR được sử dụng để điều khiển và điều chỉnh hệ thống tự động, bao gồm cả các hệ thống điều khiển trong công nghiệp và tự động hóa, phân tích và dự báo các chuỗi thời gian, giúp cải thiện hiệu suất của hệ thống điều khiển.

## Mô tả ý tưởng

**Bước 1.** Tạo các vector $u, v, q$ và 2 ma trận $Q, R$ với kích thước tương ứng. 

**Bước 2.** Áp dụng giải thuật Gram-Schmidt để tạo hệ trực giao ${v_{1}, v_{2},..., v_{n}}$. Kiểm tra hệ vector $v$ có độc lập tuyến tính không. Nếu không, kết thúc thuật toán. Ngược lại, chuẩn hóa chúng để thu được hệ trực chuẩn ${q_{1}, q_{2},..., q_{n}}$. Viết các hàm tính toán trên ma trận nếu cần thiết.

**Bước 3.** Từ hệ trực chuẩn ta xác định được ma trận $Q$. Sau đó xác định ma trận $R$. 

**Bước 4.** Tìm hiểu về các ứng dụng của giải thuật phân rã $QR$ trong thực tế.

## Mô tả các hàm

### Bài 1:

**Các hàm phụ trợ:**

&emsp;&emsp;**def dot_product(u, v)**: Tính tích vô hướng của hai vector $u$ và $v$.

&emsp;&emsp;**def vector_product(u, v)**: Tính tích giữa vector $u$ và số $v$.

&emsp;&emsp;**def vector_substract(u, v)**: Tính hiệu giữa hai vector $u$ và $v$.

&emsp;&emsp;**def vector_devide(u, v)**: Tính thương giữa vector $u$ và số $v$.

**Hàm chính:**

&emsp;&emsp;**def QR_Decomposition(A)**: Giải thuật Gram-Schimidt, in ra hai ma trận $Q$ và $R$ thỏa $A = QR$.

### Bài 2: 

Trong thư viện *numpy* của Python, module **'linalg'** (linear algebra) cung cấp phép phân rã QR. Cụ thể, hàm **'numpy.linalg.qr()'** được sử dụng để phân rã một ma trận thành tích của hai ma trận $Q$ và $R$ trong phép phân rã $QR$.